### PR TITLE
added a readDouble function

### PR DESCRIPTION
**Pull request by The-Faulty**

### CODE REVIEW

**Comment by erfg12** [comment]
Why did you update the version to 1.2.111?

**Comment by hollow87** [comment]
Might want to not round unless the user wants to and those values that it must be between are rather limited.

**Comment by erfg12** [comment]
@The-Faulty If you don't want to fix it, I can add it.

**Comment by erfg12** [comment]
Added readDouble with round option in commit c989f5108de721914ba806b4919c4428cc4f42f7

**Pull request closed without merging**
